server:
  port: 5050

spring:
  application:
    name: ms-config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/yheysonramos10/HotelSystem.git # repositorio
          searchPaths:
            - config-data
          default-label: eventsAndOthers

  security:
    user:
      name: root
      password: 123456